kind: Service
apiVersion: v1
metadata:
  name: {{ include "openresty-art.fullname" . }}-srv
  labels:
    {{- include "openresty-art.labels" . | nindent 4 }}

spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    k8s-app: openresty
